### ISSUE TITLE
Welcome adding LSK to MMRotate1. x

### ISSUE THREAD

**Issue by zytx121** [zcablii/Large-Selective-Kernel-Network#1]
Hi @zcablii, thanks for your excellent work. Welcome adding this model to MMRotate1. x to let more people see it and further increase the impact of your work. If you need any assistance, please contact me! 

The following is an example of a project:
https://github.com/open-mmlab/mmrotate/tree/dev-1.x/projects/example_project

**Comment by implus** [comment]
Thanks a lot for the invitation. We will move on and contribute to MMRotate.

**Comment by jsxyhelu** [comment]
If it can be merged, it will definitely promote the future research work, and I am willing to join this useful work!
