### ISSUE TITLE
[Question] Where exactly is the `Large Kernel Decomposition` in the code?

### ISSUE THREAD

**Issue by Henning742** [zcablii/Large-Selective-Kernel-Network#12]
### What's the feature?

Hi, I managed to find the source file `models/backbones/lsknet.py` but I can't seem to find where the decomposition is happening in the code.

If I understood correctly, `class DWConv` is the depthwise conv and `class Block` is the LSK Module. According to Fig. 4 in the paper, there should be at least 2 `DWConv` in each `Block` but I could only find one in `Block`->`Mlp`.

Help is very appreciated!

**Comment by zcablii** [comment]
`class LSKblock `  is the LSK Module, where `self.conv0` and `self.conv_spatial` are the decomposed kernels.
