### ISSUE TITLE
pre-trained weights

### ISSUE THREAD

**Issue by aupilot** [zcablii/Large-Selective-Kernel-Network#2]
### What's the feature?

Hi, 
I'm trying to download weights, but the link suggests me in Chinese to install beidu net drive instead. Could you please put the weights to some hassle-free server such as github or google drive.
Thank you!

**Comment by samuelkoes** [comment]
I have similar issue here, can not even create an account with Baidu anyway - it does not seem to accept Germany's phone number. Would greatly appreciate putting it on such server alternative, e.g. github or google drive

**Comment by zcablii** [comment]
https://we.tl/t-9QfS92vlyD?utm_campaign=TRN_TDL_09&utm_source=sendgrid&utm_medium=email&trk=TRN_TDL_09
Try this.

**Comment by 310war** [comment]
作者您好，您提供的预训练权重里的data.pkl似乎存在问题打不开
![image](https://user-images.githubusercontent.com/126972159/227778901-22111cc1-ff16-4ee9-bc8e-39db04937349.png)

**Comment by samuelkoes** [comment]
> https://we.tl/t-9QfS92vlyD?utm_campaign=TRN_TDL_09&utm_source=sendgrid&utm_medium=email&trk=TRN_TDL_09 Try this.

Thanks! Will test this out later...

**Comment by aupilot** [comment]
Thank you! that works

**Comment by zcablii** [comment]
> 作者您好，您提供的预训练权重里的data.pkl似乎存在问题打不开 ![image](https://user-images.githubusercontent.com/126972159/227778901-22111cc1-ff16-4ee9-bc8e-39db04937349.png)

请问是哪个权重文件？我提供的好像没有data.pkl。关于加载权重文件，建议使用和参考本仓库中基于mmcv的加载方式

**Comment by 310war** [comment]
> > 作者您好，您提供的预训练权重里的data.pkl似乎存在问题打不开 ![image](https://user-images.githubusercontent.com/126972159/227778901-22111cc1-ff16-4ee9-bc8e-39db04937349.png)
> 
> 请问是哪个权重文件？我提供的好像没有data.pkl。关于加载权重文件，建议使用和参考本仓库中基于mmcv的加载方式



> > 作者您好，您提供的预训练权重里的data.pkl似乎存在问题打不开 ![image](https://user-images.githubusercontent.com/126972159/227778901-22111cc1-ff16-4ee9-bc8e-39db04937349.png)
> 
> 请问是哪个权重文件？我提供的好像没有data.pkl。关于加载权重文件，建议使用和参考本仓库中基于mmcv的加载方式

是lsk_s_backbone.pth.tar解压缩里的

**Comment by 310war** [comment]
> > 作者您好，您提供的预训练权重里的data.pkl似乎存在问题打不开 ![image](https://user-images.githubusercontent.com/126972159/227778901-22111cc1-ff16-4ee9-bc8e-39db04937349.png)
> 
> 请问是哪个权重文件？我提供的好像没有data.pkl。关于加载权重文件，建议使用和参考本仓库中基于mmcv的加载方式

如果不是使用这个data.pkl，那在测试时checkpoints/SOME_CHECKPOINT.pth这个该从哪里找

**Comment by zcablii** [comment]
> > > 作者您好，您提供的预训练权重里的data.pkl似乎存在问题打不开 ![image](https://user-images.githubusercontent.com/126972159/227778901-22111cc1-ff16-4ee9-bc8e-39db04937349.png)
> > 
> > 
> > 请问是哪个权重文件？我提供的好像没有data.pkl。关于加载权重文件，建议使用和参考本仓库中基于mmcv的加载方式
> 
> > > 作者您好，您提供的预训练权重里的data.pkl似乎存在问题打不开 ![image](https://user-images.githubusercontent.com/126972159/227778901-22111cc1-ff16-4ee9-bc8e-39db04937349.png)
> > 
> > 
> > 请问是哪个权重文件？我提供的好像没有data.pkl。关于加载权重文件，建议使用和参考本仓库中基于mmcv的加载方式
> 
> 是lsk_s_backbone.pth.tar解压缩里的

请不要解压.pth.tar文件，就像配置文件中那样，直接加载这个文件就可以。
`backbone=dict(
        type='LSKNet',
        embed_dims=[64, 128, 320, 512],
        drop_rate=0.1,
        drop_path_rate=0.1,
        depths=[2,2,4,2],
        init_cfg=dict(type='Pretrained', checkpoint="/data/pretrained/lsk_s_backbone.pth.tar"),
        norm_cfg=dict(type='SyncBN', requires_grad=True)),
`

**Comment by zcablii** [comment]
> > > 作者您好，您提供的预训练权重里的data.pkl似乎存在问题打不开 ![image](https://user-images.githubusercontent.com/126972159/227778901-22111cc1-ff16-4ee9-bc8e-39db04937349.png)
> > 
> > 
> > 请问是哪个权重文件？我提供的好像没有data.pkl。关于加载权重文件，建议使用和参考本仓库中基于mmcv的加载方式
> 
> 如果不是使用这个data.pkl，那在测试时checkpoints/SOME_CHECKPOINT.pth这个该从哪里找

预训练好的检测模型权重文件和对应的配置及文件在README.md的表格中已给出。[https://pan.baidu.com/share/init?surl=dYfSldDDWWlqRfljLlYhvA&pwd=v55f](url)

**Comment by 310war** [comment]
> > > > 作者您好，您提供的预训练权重里的data.pkl似乎存在问题打不开 ![image](https://user-images.githubusercontent.com/126972159/227778901-22111cc1-ff16-4ee9-bc8e-39db04937349.png)
> > > 
> > > 
> > > 请问是哪个权重文件？我提供的好像没有data.pkl。关于加载权重文件，建议使用和参考本仓库中基于mmcv的加载方式
> > 
> > 
> > 如果不是使用这个data.pkl，那在测试时checkpoints/SOME_CHECKPOINT.pth这个该从哪里找
> 
> 预训练好的检测模型权重文件和对应的配置及文件在README.md的表格中已给出。[https://pan.baidu.com/share/init?surl=dYfSldDDWWlqRfljLlYhvA&pwd=v55f](url)

已按表格一一对应 出现这个问题
![image](https://user-images.githubusercontent.com/126972159/227824638-3f05e02c-8d81-4038-ad67-2c602bae28da.png)

**Comment by zcablii** [comment]
> > > > > 作者您好，您提供的预训练权重里的data.pkl似乎存在问题打不开 ![image](https://user-images.githubusercontent.com/126972159/227778901-22111cc1-ff16-4ee9-bc8e-39db04937349.png)
> > > > 
> > > > 
> > > > 请问是哪个权重文件？我提供的好像没有data.pkl。关于加载权重文件，建议使用和参考本仓库中基于mmcv的加载方式
> > > 
> > > 
> > > 如果不是使用这个data.pkl，那在测试时checkpoints/SOME_CHECKPOINT.pth这个该从哪里找
> > 
> > 
> > 预训练好的检测模型权重文件和对应的配置及文件在README.md的表格中已给出。[https://pan.baidu.com/share/init?surl=dYfSldDDWWlqRfljLlYhvA&pwd=v55f](url)
> 
> 已按表格一一对应 出现这个问题 ![image](https://user-images.githubusercontent.com/126972159/227824638-3f05e02c-8d81-4038-ad67-2c602bae28da.png)

请检查一下你用来test的数据路径是否设置正确。
