### ISSUE TITLE
[Docs] 

### ISSUE THREAD

**Issue by yoloyash** [zcablii/Large-Selective-Kernel-Network#3]
### Branch

master branch  https://mmrotate.readthedocs.io/en/latest/

### 📚 The doc issue

Hello, really amazing work and repository! I had a doubt, I'm training on a Tesla T4 15GB on a relatively small dataset. I have put samples_per_gpu=1, workers_per_gpu=2. However, I'm still going out of memory. To be precise, the model trains 1 epoch perfectly but during the val after the epoch it launches 4 python processes (as seen in Nvidia-smi). The images are 1024x1024. I have even tried to remove the PolyRandomRotate augmentations. How come the model is training perfectly 1 epoch and giving error only during validation? Sorry if this is posted in the wrong place.

### Suggest a potential alternative/fix
<img width="571" alt="Screenshot 2023-03-28 at 12 01 10 AM" src="https://user-images.githubusercontent.com/26775473/228034303-a784ddf3-b306-480e-b1c5-f11cbf96273c.png">

_No response_

**Comment by zcablii** [comment]
Not sure why this is happening, I've never had this problem before,. Maybe you could try fp16 by setting `fp16 = dict(loss_scale='dynamic')` or setting `gpu_assign_thr=600` in the config files. That might save more video memory.
