### ISSUE TITLE
代码中没有提供lsk_s_backbone.pth.tar文件

### ISSUE THREAD

**Issue by 2276924877** [zcablii/Large-Selective-Kernel-Network#4]
### Branch

master branch  https://mmrotate.readthedocs.io/en/latest/

### 📚 The doc issue

作者你好，我下载此代码压缩包，发现代码中没有提供lsk_s_backbone.pth.tar文件

**Comment by zcablii** [comment]
Links to download the relevant pretrained backbones are available in README. I'll paste it here again: https://download.openmmlab.com/mmrotate/v1.0/lsknet/backbones/lsk_s_backbone-e9d2e551.pth

**Comment by 2276924877** [comment]
How do I modify the configuration file? The file extension seems to be different.
`init_cfg=dict(type='Pretrained', checkpoint="/data/pretrained/lsk_s_backbone.pth.tar")`

**Comment by zcablii** [comment]
No worries, just load as it is:  init_cfg=dict(type='Pretrained', checkpoint="PATH_TO_YOUR_DOWNLOADED_CKPTS/lsk_s_backbone-e9d2e551.pth")

**Comment by 2276924877** [comment]
Firstly, thank you very much for answering my question. Secondly, I would like to ask another question.I only have one GPU. How should I train my model?I modified the code lsk_s_fpn_1x_dota_le90.py in this way, but the results after training are not satisfactory.
`    backbone=dict(
        type='LSKNet',
        embed_dims=[64, 128, 320, 512],
        drop_rate=0.1,
        drop_path_rate=0.1,
        depths=[2, 2, 4, 2],
        init_cfg=dict(
            type='Pretrained',
            checkpoint=
            '/data/gm/Large-Selective-Kernel-Network-main/data/pretrained/lsk_s_backbone.pth'
        ),
        **norm_cfg=dict(type='BN', requires_grad=True))**,`

**Comment by zcablii** [comment]
I am afraid that the main influence on your reproduction results here is the mismatch between batch-size and learning-rate. I would suggest that you adjust your learning-rate linearly to the provided learning-rate. The exact relationship is lr = (your_batchsize) / (default_batchsize) * 0.0002, where default_batchsize is 8 in the provided config file. In your case (if I assume your batch-size is 1), lr should be set to around 0.000025. 
This can only resolve the conflict between learning-rate and batch-size, but a small batch-size is expected to yield a lower performance.

**Comment by nyjshinibaba** [comment]
如果我要在八卡机上单卡跑你的模型应该用什么指令

**Comment by zcablii** [comment]
单卡跑：
python tools/train.py ${CONFIG_FILE} [optional arguments]


一开始会卡住是因为要筛查选数据，需要等一段时间。



发件人: ***@***.***>
发送时间: 2023年9月21日 15:32
收件人: ***@***.***>
抄送: Li, ***@***.***>; ***@***.***>
主题: Re: [zcablii/LSKNet] 代码中没有提供lsk_s_backbone.pth.tar文件 (Issue #4)


如果我要在八卡机上单卡跑你的模型应该用什么指令

―

**Comment by LKXHZD** [comment]
出现这个情况，怎么调节batch_size、samples_per_gpu、workers_per_gpu和学习率啊？求解，非常感谢！
RuntimeError: DataLoader worker (pid 10475) is killed by signal: Terminated.

**Comment by xifen523** [comment]
> Links to download the relevant pretrained backbones are available in README. I'll paste it here again: https://download.openmmlab.com/mmrotate/v1.0/lsknet/backbones/lsk_s_backbone-e9d2e551.pth

it‘s not work

**Comment by zcablii** [comment]
> > Links to download the relevant pretrained backbones are available in README. I'll paste it here again: https://download.openmmlab.com/mmrotate/v1.0/lsknet/backbones/lsk_s_backbone-e9d2e551.pth
> 
> it‘s not work

It works for me. Maybe switch your network and try again?
