### ISSUE TITLE
LSKNet is not in the models registry

### ISSUE THREAD

**Issue by jsxyhelu** [zcablii/Large-Selective-Kernel-Network#8]
When I try to get through the code here, I get the following error, what should I do? Thank~

`KeyError: "OrientedRCNN: 'LSKNet is not in the models registry'"`

**Comment by zcablii** [comment]
Could you please provide more information on your error?

**Comment by zcablii** [comment]
It seems that you did not install mmrotate correctly, please try to reinstall mmrotate according to the readme step by step.

**Comment by Z-ZHHH** [comment]
I ve also met this problem. That can be solved by running `python setup.py install`

**Comment by jsxyhelu** [comment]
OK，thanks,this is fine to me.

**Comment by HuangShiqi128** [comment]
I encounter the same error. However, the solution in above comments doesn't seem to solve my issue. Are there any other solutions?

**Comment by imnoootdreaming** [comment]
> I ve also met this problem. That can be solved by running `python setup.py install`
Thanks a lot!
